name: Testing-Action

on: 
  pull_request: 
        types: 
           - opened

jobs:
  testing-action:
    runs-on: ubuntu-latest
    permissions: 
        issues: write
        pull-requests: write
    steps:
      - name: Post PR comment
        uses: M0-3del/docker-action-pr-giphy-comment@main
        with:
          github-tokon: ${{ secrets.GITHUB_TOKEN }}
          giphy-api-key: ${{ secrets.GIPHY_API_KEY }}
