name: Deployment - Reuseable Workflow
on:
    workflow_call:
      inputs:
        mongodb-uri:
         required: true
         type: string
        kubctl-version:
          description: Provide the requird Kubectl version
          default: v1.26.0
          required: false
          type: string
        k8s-minfiest-dir:
          description: Dirctroy containing kubernetes mainfiest files
          default: kubernetes/
          required: true
          type: string
        enviroment:
          description: Provide the Deployment Enviroment
          default: dev
          required: true
          type: string
      outputs:
        appliction-url:
          value: ${{ jobs.reuse-deploy.APP_INGRESS_URL }}
      secrets:
        k8s-kubecngig:
          required: true
        mongodb-password:
          required: true
        
jobs:
    reuse-deploy:
        
      environment: 
        name: ${{ inputs.enviroment }}
        url: https://${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
      outputs: 
        APP_INGRESS_URL: ${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
      runs-on: ubuntu-latest
      steps:
         - name: Checkout Repo
           uses:  actions/checkout@v4
         - name: install kubctl CLI
           uses: azure/setup-kubectl@v4
           with:
             version: '${{ inputs.kubctl-version }}'
         - name: Set Kubconfing
           uses: azure/k8s-set-context@v4
           with:
              method: kubeconfig
              kubeconfig: ${{ secrets.k8s-kubecngig }}
         - name: fetch kubernetces Cluster Details
           run: |
            kubctl version --short
            echo --------------------------------
            kubctl get nodes
         - name: Save Nginx Ingress Controller IP as a GITHUB Environment Variable
           run: |
            echo "IGRESS_IP=$(kubectl -n ingress-nginx get services ingress-nginx-controller -o jsonpath="{.status.loadBalancer.ingress[0].ip}")" >> $GITHUB_ENV

         - name: Replace Token in Minfest files
           uses: cschleiden/replace-tokens@v1
           with:
             tokenPrefix: '_{_'
             tokenSuffix: '_}_'
             files: '["${{ inputs.k8s-minfist-dir }}*.yaml"]'
           env:
             NAMESPACE: ${{ vars.NAMESPACE }}
             REPLICAS: ${{ vars.REPLICAS }}
             IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
             INGRESS_IP: ${{ env.IGRESS_IP }}

         - name: Check files
           run: |
            cat ${{ inputs.k8s-minfist-dir }}*.yaml

         - name:  Create Mongo Sercret
           run: |
            kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
            --from-literal=MONGO_URI=${{ inputs.mongodb-uri }}
            --from-literal=MONGO_USERNAME=${{ env.MONGO_USERNAME }}
            --from-literal=MONGO_PASSWORD=${{ secrets.mongodb-password}}
            --save-config \
            dry-run=Client \
            -o yaml | kubctl apply -f -

         - name: Deploy to PROD ENV
           run: |
            kubectl apply kubernetes/development/*.yaml

         - name: set App Ingress Host URL
           id: set-ingress-host-address
           run: |
            echo "APP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ingress -o jsonpath="{.items[0].spac.tls[0].hosts[0]}")" >> "$GITHUB_OUTPUT"
