name: Solar System Workflow
on:
    workflow_dispatch: 
    push:     
        branches: 
            - main
            - 'feature/*'

env:
  MONGO_URI: 'mongodb://${{ secrets.USERNAME}}:${{ vars.PASSWORD }}@cluster0.7x6u1mv.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.PASSWORD }}
  MONGO_PASSWORD: ${{ secrets.USERNAME}}
jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses:  actions/checkout@v4

            - name: Setup NodeJs Version - 18
              uses: actions/setup-node@v3
              with:
                node-version: 18

            - name: Install Dependencies
              run: npm install

            - name: Unit Testing
              run: npm test
            - name: Archive Test Result
              uses:  actions/upload-artifact@v3
              with:
                name: Mocha-Test-Resalt
                path: test-Resalt.xml


